meta:
  id: wollemi_protocol
  title: Wollemi 12U science observatory -- full protocol (all messages, CCSDS Space Packet + Wollemi secondary header)
  application: Wollemi (github.com/alplix/wollemi, private until the design is complete)
  license: Apache-2.0
  endian: be
  bit-endian: be
doc: |
  Generated by protocol/gen_kaitai.py from protocol/messages.toml (the same source protocol/gen.py uses
  for the C and Python implementations); do not edit by hand. Covers all 27 messages by switching on the CCSDS
  APID in the primary header. See protocol/gen_kaitai.py's own docstring for what is and is not verified.
seq:
  - id: primary_header
    type: primary_header
  - id: body
    type:
      switch-on: primary_header.apid
      cases:
        1: beacon_body  # beacon (SUP, tm)
        2: hk_sup_body  # hk_sup (SUP, tm)
        259: hk_fc_body  # hk_fc (FCA, tm)
        260: hk_power_body  # hk_power (FCA, tm)
        261: hk_thermal_body  # hk_thermal (FCA, tm)
        262: hk_adcs_body  # hk_adcs (FCA, tm)
        272: sci_mag_body  # sci_mag (FCA, tm)
        273: sci_tsi_body  # sci_tsi (FCA, tm)
        274: sci_dose_body  # sci_dose (FCA, tm)
        275: sci_particle_body  # sci_particle (FCA, tm)
        276: sci_xray_body  # sci_xray (FCA, tm)
        277: sci_grb_body  # sci_grb (FCA, tm)
        278: sci_csac_body  # sci_csac (FCA, tm)
        279: sci_seu_body  # sci_seu (FCA, tm)
        288: event_body  # event (FCA, tm)
        816: mmu_status_body  # mmu_status (MMU, tm)
        1585: obj_ack_body  # obj_ack (GND, tc)
        320: mode_set_body  # mode_set (FCA, tc)
        321: power_switch_body  # power_switch (FCA, tc)
        322: time_set_body  # time_set (FCA, tc)
        323: seq_load_body  # seq_load (FCA, tc)
        324: burn_schedule_body  # burn_schedule (FCA, tc)
        69: key_rotate_body  # key_rotate (SUP, tc)
        336: ota_begin_body  # ota_begin (FCA, tc)
        337: ota_commit_body  # ota_commit (FCA, tc)
        82: ota_confirm_body  # ota_confirm (SUP, tc)
        1120: relay_msg_body  # relay_msg (PAYL, public)
types:
  primary_header:
    doc: CCSDS Space Packet primary header (6 bytes), common to every Wollemi message.
    seq:
      - id: version
        type: b3
        doc: always 0 for this mission
      - id: is_tc
        type: b1
        doc: 1 = telecommand (authenticated, kind "tc"); 0 = telemetry or the public relay message
      - id: has_secondary_header
        type: b1
        doc: always 1 for this mission
      - id: apid
        type: b11
        doc: (node id << 8) | message id; selects the body type below
      - id: sequence_flags
        type: b2
        doc: always 3 (unsegmented) for this mission
      - id: sequence_count
        type: b14
      - id: packet_data_length
        type: u2
        doc: CCSDS convention -- total packet length in octets is this value + 7
  secondary_header:
    doc: Wollemi secondary header (8 bytes), common to every message.
    seq:
      - id: coarse_time
        type: u4
        doc: TAI seconds
      - id: fine_time
        type: u2
        doc: sub-second ticks, 1/65536 s
      - id: flags
        type: flags_byte
      - id: format_version
        type: u1
        doc: per-message field-layout version (increments if fields ever change)
  flags_byte:
    seq:
      - id: clock_quality
        type: b2
      - id: priority_minus_1
        type: b2
        doc: message priority - 1 (P1..P4)
      - id: reserved
        type: b4
  beacon_body:
    seq:
      - id: secondary_header
        type: secondary_header
      - id: mode
        type: u1
      - id: node_health
        type: u1
      - id: batt_a_mv
        type: u2
      - id: batt_b_mv
        type: u2
      - id: batt_c_mv
        type: u2
      - id: bus_a_mv
        type: u2
      - id: solar_ma
        type: u2
      - id: temp_body_dc
        type: s2
      - id: uptime_s
        type: u4
      - id: reset_count
        type: u2
      - id: crc16
        type: u2
        doc: CRC-16/CCITT-FALSE over every preceding byte (verify separately; not checked by this struct)
  hk_sup_body:
    seq:
      - id: secondary_header
        type: secondary_header
      - id: watchdog_flags
        type: u2
      - id: lcl_trips
        type: u2
      - id: power_state
        type: u4
      - id: last_fdir_action
        type: u2
      - id: cmd_counter
        type: u4
      - id: key_id
        type: u1
      - id: crc16
        type: u2
        doc: CRC-16/CCITT-FALSE over every preceding byte (verify separately; not checked by this struct)
  hk_fc_body:
    seq:
      - id: secondary_header
        type: secondary_header
      - id: mode
        type: u1
      - id: level
        type: u1
      - id: seq_running
        type: u2
      - id: cpu_load_pct
        type: u1
      - id: ram_free_kb
        type: u2
      - id: cmd_accepted
        type: u4
      - id: cmd_rejected
        type: u4
      - id: clock_quality
        type: u1
      - id: crc16
        type: u2
        doc: CRC-16/CCITT-FALSE over every preceding byte (verify separately; not checked by this struct)
  hk_power_body:
    seq:
      - id: secondary_header
        type: secondary_header
      - id: pack_a_mv
        type: u2
      - id: pack_b_mv
        type: u2
      - id: pack_c_mv
        type: u2
      - id: pack_a_ma
        type: s2
      - id: pack_b_ma
        type: s2
      - id: pack_c_ma
        type: s2
      - id: solar_string_ma
        size: 12
      - id: soc_a_pct
        type: u1
      - id: soc_b_pct
        type: u1
      - id: load_mw
        type: u4
      - id: gen_mw
        type: u4
      - id: lcl_state
        type: u4
      - id: crc16
        type: u2
        doc: CRC-16/CCITT-FALSE over every preceding byte (verify separately; not checked by this struct)
  hk_thermal_body:
    seq:
      - id: secondary_header
        type: secondary_header
      - id: temp_dc
        size: 32
      - id: heater_state
        type: u2
      - id: radiator_state
        type: u1
      - id: crc16
        type: u2
        doc: CRC-16/CCITT-FALSE over every preceding byte (verify separately; not checked by this struct)
  hk_adcs_body:
    seq:
      - id: secondary_header
        type: secondary_header
      - id: quat
        size: 16
      - id: rate_mdps
        size: 6
      - id: wheel_rpm
        size: 8
      - id: pointing_mode
        type: u1
      - id: sun_angle_cdeg
        type: u2
      - id: crc16
        type: u2
        doc: CRC-16/CCITT-FALSE over every preceding byte (verify separately; not checked by this struct)
  sci_mag_body:
    seq:
      - id: secondary_header
        type: secondary_header
      - id: t0_fine
        type: u2
      - id: n
        type: u1
      - id: samples
        size: 96
      - id: temp_dc
        type: s2
      - id: crc16
        type: u2
        doc: CRC-16/CCITT-FALSE over every preceding byte (verify separately; not checked by this struct)
  sci_tsi_body:
    seq:
      - id: secondary_header
        type: secondary_header
      - id: irradiance_mw_m2
        type: u4
      - id: cavity_temp_dc
        type: s2
      - id: shutter
        type: u1
      - id: quality
        type: u1
      - id: crc16
        type: u2
        doc: CRC-16/CCITT-FALSE over every preceding byte (verify separately; not checked by this struct)
  sci_dose_body:
    seq:
      - id: secondary_header
        type: secondary_header
      - id: dose_urad
        type: u4
      - id: counts_low
        type: u4
      - id: counts_high
        type: u4
      - id: temp_dc
        type: s2
      - id: crc16
        type: u2
        doc: CRC-16/CCITT-FALSE over every preceding byte (verify separately; not checked by this struct)
  sci_particle_body:
    seq:
      - id: secondary_header
        type: secondary_header
      - id: integ_ds
        type: u2
      - id: electrons
        size: 32
      - id: protons
        size: 32
      - id: crc16
        type: u2
        doc: CRC-16/CCITT-FALSE over every preceding byte (verify separately; not checked by this struct)
  sci_xray_body:
    seq:
      - id: secondary_header
        type: secondary_header
      - id: integ_ds
        type: u2
      - id: bands
        size: 16
      - id: flare_flag
        type: u1
      - id: crc16
        type: u2
        doc: CRC-16/CCITT-FALSE over every preceding byte (verify separately; not checked by this struct)
  sci_grb_body:
    seq:
      - id: secondary_header
        type: secondary_header
      - id: t0_fine
        type: u2
      - id: counts
        size: 64
      - id: trigger_flag
        type: u1
      - id: crc16
        type: u2
        doc: CRC-16/CCITT-FALSE over every preceding byte (verify separately; not checked by this struct)
  sci_csac_body:
    seq:
      - id: secondary_header
        type: secondary_header
      - id: offset_ns
        type: s4
      - id: lock
        type: u1
      - id: temp_dc
        type: s2
      - id: crc16
        type: u2
        doc: CRC-16/CCITT-FALSE over every preceding byte (verify separately; not checked by this struct)
  sci_seu_body:
    seq:
      - id: secondary_header
        type: secondary_header
      - id: sram_flips
        type: u4
      - id: fram_flips
        type: u4
      - id: nand_slc_errs
        type: u4
      - id: nand_tlc_errs
        type: u4
      - id: nand_qlc_errs
        type: u4
      - id: jetson_err
        type: u2
      - id: cm5_err
        type: u2
      - id: mcu_err
        type: u2
      - id: crc16
        type: u2
        doc: CRC-16/CCITT-FALSE over every preceding byte (verify separately; not checked by this struct)
  event_body:
    seq:
      - id: secondary_header
        type: secondary_header
      - id: event_id
        type: u2
      - id: severity
        type: u1
      - id: source_node
        type: u1
      - id: arg0
        type: u4
      - id: arg1
        type: u4
      - id: crc16
        type: u2
        doc: CRC-16/CCITT-FALSE over every preceding byte (verify separately; not checked by this struct)
  mmu_status_body:
    seq:
      - id: secondary_header
        type: secondary_header
      - id: devices_alive
        type: u1
      - id: stripe_data
        type: u1
      - id: stripe_parity
        type: u1
      - id: used_gb
        type: u2
      - id: free_gb
        type: u2
      - id: scrub_pct
        type: u1
      - id: corrected_errs
        type: u4
      - id: uncorrectable
        type: u2
      - id: crc16
        type: u2
        doc: CRC-16/CCITT-FALSE over every preceding byte (verify separately; not checked by this struct)
  obj_ack_body:
    seq:
      - id: secondary_header
        type: secondary_header
      - id: counter
        type: u4
      - id: valid_until
        type: u4
      - id: object_id
        type: u4
      - id: hash8
        size: 8
      - id: signature
        size: 64
        doc: Ed25519 signature over everything from the primary header through the payload (verified by firmware/common/wl_auth.c, not by this decoder)
      - id: crc16
        type: u2
        doc: CRC-16/CCITT-FALSE over every preceding byte (verify separately; not checked by this struct)
  mode_set_body:
    seq:
      - id: secondary_header
        type: secondary_header
      - id: counter
        type: u4
      - id: valid_until
        type: u4
      - id: mode
        type: u1
      - id: reason
        type: u1
      - id: signature
        size: 64
        doc: Ed25519 signature over everything from the primary header through the payload (verified by firmware/common/wl_auth.c, not by this decoder)
      - id: crc16
        type: u2
        doc: CRC-16/CCITT-FALSE over every preceding byte (verify separately; not checked by this struct)
  power_switch_body:
    seq:
      - id: secondary_header
        type: secondary_header
      - id: counter
        type: u4
      - id: valid_until
        type: u4
      - id: lcl_id
        type: u1
      - id: state
        type: u1
      - id: signature
        size: 64
        doc: Ed25519 signature over everything from the primary header through the payload (verified by firmware/common/wl_auth.c, not by this decoder)
      - id: crc16
        type: u2
        doc: CRC-16/CCITT-FALSE over every preceding byte (verify separately; not checked by this struct)
  time_set_body:
    seq:
      - id: secondary_header
        type: secondary_header
      - id: counter
        type: u4
      - id: valid_until
        type: u4
      - id: coarse
        type: u4
      - id: fine
        type: u2
      - id: mode
        type: u1
      - id: signature
        size: 64
        doc: Ed25519 signature over everything from the primary header through the payload (verified by firmware/common/wl_auth.c, not by this decoder)
      - id: crc16
        type: u2
        doc: CRC-16/CCITT-FALSE over every preceding byte (verify separately; not checked by this struct)
  seq_load_body:
    seq:
      - id: secondary_header
        type: secondary_header
      - id: counter
        type: u4
      - id: valid_until
        type: u4
      - id: slot
        type: u2
      - id: trigger_type
        type: u1
      - id: trigger_value
        type: u4
      - id: cmd_apid
        type: u2
      - id: cmd_args
        size: 16
      - id: signature
        size: 64
        doc: Ed25519 signature over everything from the primary header through the payload (verified by firmware/common/wl_auth.c, not by this decoder)
      - id: crc16
        type: u2
        doc: CRC-16/CCITT-FALSE over every preceding byte (verify separately; not checked by this struct)
  burn_schedule_body:
    seq:
      - id: secondary_header
        type: secondary_header
      - id: counter
        type: u4
      - id: valid_until
        type: u4
      - id: start_coarse
        type: u4
      - id: duration_s
        type: u4
      - id: dir_x_mm
        type: s2
      - id: dir_y_mm
        type: s2
      - id: dir_z_mm
        type: s2
      - id: thrust_pct
        type: u1
      - id: signature
        size: 64
        doc: Ed25519 signature over everything from the primary header through the payload (verified by firmware/common/wl_auth.c, not by this decoder)
      - id: crc16
        type: u2
        doc: CRC-16/CCITT-FALSE over every preceding byte (verify separately; not checked by this struct)
  key_rotate_body:
    seq:
      - id: secondary_header
        type: secondary_header
      - id: counter
        type: u4
      - id: valid_until
        type: u4
      - id: key_id
        type: u1
      - id: pubkey
        size: 32
      - id: root_sig
        size: 64
      - id: signature
        size: 64
        doc: Ed25519 signature over everything from the primary header through the payload (verified by firmware/common/wl_auth.c, not by this decoder)
      - id: crc16
        type: u2
        doc: CRC-16/CCITT-FALSE over every preceding byte (verify separately; not checked by this struct)
  ota_begin_body:
    seq:
      - id: secondary_header
        type: secondary_header
      - id: counter
        type: u4
      - id: valid_until
        type: u4
      - id: target_node
        type: u1
      - id: slot
        type: u1
      - id: size
        type: u4
      - id: hash
        size: 32
      - id: signature
        size: 64
        doc: Ed25519 signature over everything from the primary header through the payload (verified by firmware/common/wl_auth.c, not by this decoder)
      - id: crc16
        type: u2
        doc: CRC-16/CCITT-FALSE over every preceding byte (verify separately; not checked by this struct)
  ota_commit_body:
    seq:
      - id: secondary_header
        type: secondary_header
      - id: counter
        type: u4
      - id: valid_until
        type: u4
      - id: target_node
        type: u1
      - id: slot
        type: u1
      - id: confirm_timeout_s
        type: u2
      - id: signature
        size: 64
        doc: Ed25519 signature over everything from the primary header through the payload (verified by firmware/common/wl_auth.c, not by this decoder)
      - id: crc16
        type: u2
        doc: CRC-16/CCITT-FALSE over every preceding byte (verify separately; not checked by this struct)
  ota_confirm_body:
    seq:
      - id: secondary_header
        type: secondary_header
      - id: counter
        type: u4
      - id: valid_until
        type: u4
      - id: target_node
        type: u1
      - id: slot
        type: u1
      - id: signature
        size: 64
        doc: Ed25519 signature over everything from the primary header through the payload (verified by firmware/common/wl_auth.c, not by this decoder)
      - id: crc16
        type: u2
        doc: CRC-16/CCITT-FALSE over every preceding byte (verify separately; not checked by this struct)
  relay_msg_body:
    seq:
      - id: secondary_header
        type: secondary_header
      - id: from_call
        size: 8
      - id: to_call
        size: 8
      - id: msg_id
        type: u2
      - id: text
        size: 64
      - id: crc16
        type: u2
        doc: CRC-16/CCITT-FALSE over every preceding byte (verify separately; not checked by this struct)
