"""Run every analysis and test in the repository and write docs/status.md.

Usage: python tools/check_all.py [--quick]
--quick skips the slow CAD/thermal runs. Exit code 1 if any check fails.
Each entry is (name, command, pass condition text found in the output or exit code 0, summary regex).
"""
import os
import re
import subprocess
import sys
import time
from datetime import datetime, timezone

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PY = sys.executable

CHECKS = [
    # name, command, must-contain (None = exit code only), summary regex, slow
    ("Budget (mass, power, volume)", [PY, "sim/budget.py", "configs/12u_science.toml"], None, r"Mass:.*|FOM-3 payload:.*", False),
    ("Layout rules", [PY, "sim/layout_check.py"], "[OK  ] pack A and pack B", r"Column totals:.*", False),
    ("Centre of mass and heat per column", [PY, "sim/balance.py"], "BOL CoM", r"BOL CoM offset.*", False),
    ("Data budget", [PY, "sim/data_budget.py"], "S-band per pass", r"S-band per pass.*", False),
    ("Longevity", [PY, "sim/longevity.py"], "cycle life", r"Main packs no longer.*", False),
    ("Link budget", [PY, "sim/link_budget.py"], "dish", r"1\.2m.*", False),
    ("EPS design", [PY, "sim/eps_design.py"], "OK", r"Pack: .*", False),
    ("ADCS sizing", [PY, "sim/adcs.py"], "Verdict", r"Candidate wheels.*", False),
    ("Protocol tests", [PY, "protocol/tests/test_protocol.py"], "ALL PASSED", r"C cross-check:.*", False),
    ("Firmware tests", [PY, "firmware/tests/run_tests.py"], "ALL FIRMWARE TESTS PASSED", r"authentication cross-checks:.*", False),
    ("Thermal model", [PY, "sim/thermal.py"], "NOMINAL, dawn-dusk", r"NOMINAL, dawn-dusk.*", True),
    ("Geometric packing", [PY, "mechanical/pack.py"], "All modules placed", r"Whole interior.*", False),
    ("CAD assembly and checks", [PY, "mechanical/ginkgo_cad.py"], "0 interferences", r"\d+ overlapping.*", True),
    ("Verification matrix", [PY, "sim/trace_check.py"], "0 auto FAIL", r"\d+ requirements:.*", True),
]

OPTIONAL = [
    # entries appended by later steps: (name, path that must exist, command, must-contain, summary regex, slow)
    ("Structural analysis", "sim/structure.py", [PY, "sim/structure.py"], "Verdict", r"Verdict.*", False),
    ("Orbit lifetime", "sim/orbit_life.py", [PY, "sim/orbit_life.py"], "Verdict", r"Verdict.*", False),
    ("Mission simulation", "sim/mission_sim.py", [PY, "sim/mission_sim.py"], "Verdict", r"Verdict.*", True),
    ("Cost estimate", "sim/cost.py", [PY, "sim/cost.py"], "Total", r"Total.*", False),
    ("FMEA coverage", "tools/fmea_check.py", [PY, "tools/fmea_check.py"], "FMEA coverage OK", r"FMEA coverage.*", False),
    ("Requirements sync", "tools/req_sync_check.py", [PY, "tools/req_sync_check.py"], "REQ SYNC OK", r"REQ SYNC.*", False),
    ("Test plan coverage", "tools/test_plan_check.py", [PY, "tools/test_plan_check.py"], "TEST PLAN coverage OK", r"TEST PLAN coverage.*", False),
]


def run(name, cmd, must, pattern):
    t0 = time.time()
    try:
        r = subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True, timeout=1800)
        out = r.stdout + r.stderr
        ok = r.returncode == 0 and (must is None or must in out)
    except subprocess.TimeoutExpired:
        out, ok = "timeout", False
    summary = ""
    for m in re.finditer(pattern, out):
        summary = m.group(0).strip()
    return ok, summary[:150], time.time() - t0


def main():
    quick = "--quick" in sys.argv
    rows = []
    checks = [(n, c, m, p) for n, c, m, p, slow in CHECKS if not (quick and slow)]
    checks += [(n, c, m, p) for n, path, c, m, p, slow in OPTIONAL if os.path.exists(os.path.join(ROOT, path)) and not (quick and slow)]
    for name, cmd, must, pat in checks:
        ok, summary, dt = run(name, cmd, must, pat)
        rows.append((name, ok, summary, dt))
        print(f"[{'PASS' if ok else 'FAIL'}] {name:34s} {dt:6.1f} s  {summary}")
    failed = [r for r in rows if not r[1]]
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    md = ["# Status (generated)", "", f"Generated by `python tools/check_all.py` on {stamp}. Do not edit by hand.", "",
          f"**{len(rows) - len(failed)} of {len(rows)} checks pass.**", "", "| Check | Result | Key output |", "|---|---|---|"]
    for name, ok, summary, dt in rows:
        md.append(f"| {name} | {'PASS' if ok else '**FAIL**'} | {summary.replace('|', '/')} |")
    md += ["", "All figures are analysis results on engineering estimates; see `docs/plan.md` for what remains and `docs/risks.md` for what could go wrong."]
    open(os.path.join(ROOT, "docs", "status.md"), "w", encoding="utf-8").write("\n".join(md) + "\n")
    print(f"\n{len(rows) - len(failed)}/{len(rows)} checks pass; wrote docs/status.md")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
