"""Generate docs/icd.md (interface control document) from the live design data.

Usage: python tools/gen_icd.py
Every number in the tables is read from the configs or computed by the analysis tools, so the ICD cannot drift from the design.
"""
import json
import os
import sys
import tomllib

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "sim"))
sys.path.insert(0, os.path.join(ROOT, "mechanical"))
import budget  # noqa: E402
import ginkgo_cad as gc  # noqa: E402


def load(p):
    return tomllib.load(open(os.path.join(ROOT, p), "rb"))


def main():
    cfg = load("configs/12u_science.toml")
    geo = load("configs/12u_geometry.toml")
    st = load("configs/12u_structure.toml")
    data = load("configs/12u_data.toml")
    pin = load("electronics/card_pinout.toml")
    placement = json.load(open(os.path.join(ROOT, "mechanical", "out", "placement.json")))
    r = budget.compute(cfg)
    M, com, inertia = gc.mass_props(placement["placed"], cfg, False, geo)
    Md, comd, inertia_d = gc.mass_props(placement["placed"], cfg, True, geo)
    fr = geo["frame"]
    wg = geo["wings"]
    ox, oy, oz = fr["outer"]
    stack = wg["panels_per_wing"] * wg["panel"][2]
    span = 2 * (ox / 2 + wg["panels_per_wing"] * wg["panel"][0])
    safe = next(s for s in r["scenarios"] if s["safe"])["cons"]
    n_gkp = len(pin["gkp"]["pairs"]) * 2
    n_gkd = len(pin["gkd"]["pairs"]) * 2
    link = data["link"]

    L = []
    a = L.append
    a("# Interface control document (generated)")
    a("")
    a("Generated by `python tools/gen_icd.py` from the configs and analysis tools; do not edit by hand. Every value is a design value (analysis or estimate) unless a source is named;")
    a("the launch-provider values in section 6 are assumptions to be replaced by the provider's interface requirements document.")
    a("")
    a("## 1. Mechanical interfaces")
    a("")
    a("| Item | Value | Source |")
    a("|---|---|---|")
    a(f"| Form factor | 12U CubeSat, envelope {ox:.1f} x {oy:.1f} x {oz:.1f} mm, rails {fr['rail']} mm | `configs/12u_geometry.toml` |")
    a(f"| Mass at launch | {r['mass_kg']:.2f} kg (limit 24 kg) | `sim/budget.py` |")
    a(f"| Centre of mass (offset from the geometric centre) | ({com[0]:+.1f}, {com[1]:+.1f}, {com[2]:+.1f}) mm stowed; ({comd[0]:+.1f}, {comd[1]:+.1f}, {comd[2]:+.1f}) mm wings deployed | `mechanical/ginkgo_cad.py` |")
    a(f"| Moments of inertia (kg m2) | stowed ({inertia[0]:.3f}, {inertia[1]:.3f}, {inertia[2]:.3f}); deployed ({inertia_d[0]:.3f}, {inertia_d[1]:.3f}, {inertia_d[2]:.3f}) | same |")
    a(f"| Stowed wing stack thickness | {stack:.1f} mm (allowed protrusion {fr['protrusion_limit']} mm), six hold-down posts per wing | `docs/structure.md` |")
    a(f"| External protrusions | patch antennas 4 mm; thruster nozzle flush; boom and UHF antenna stowed inside the envelope | CAD |")
    a(f"| Deployables | 2 wings x {wg['panels_per_wing']} panels ({wg['panel'][0]:.0f} x {wg['panel'][1]:.0f} x {wg['panel'][2]} mm, cells both faces), deployed span {span:.0f} mm; magnetometer boom and UHF antenna (lengths to be fixed) | CAD |")
    a(f"| Internal architecture | 2 x 2 x 3 cell grid, central spine 40 mm, notched card 100 x 100 mm (20 mm notch, 8 mm relief), 4 mm backplane gap | `docs/layout.md`, `docs/electrical-interface.md` |")
    a(f"| Number of modules | {len(placement['placed'])} placed with 0 interferences | CAD check |")
    a("")
    a("## 2. Electrical interfaces")
    a("")
    a("| Item | Value |")
    a("|---|---|")
    a("| Main bus | VBAT_A and VBAT_B, 2S LiFePO4 5.0 - 7.3 V (nominal 6.4 V); cards accept 4.5 - 8.6 V; every card has its own eFuse (trip 1.5x nominal) |")
    a(f"| Card connectors | GK-P {n_gkp} pins (power, CAN-FD A/B, PPS, SYNC, SLOT_ID, SLOT_SEL, KILL_N, FAULT_N, RESET_N, I2C, UART, SWD) and GK-D {n_gkd} pins (Ethernet, fast lanes), pitch {pin['card']['connector_pitch']} mm |")
    a("| Backplane | 15 slots plus hub per column, bussed signals daisy-chained, GND and battery planes (`electronics/gen_backplane.py`, DRC clean) |")
    a("| Battery packs | A and B: 2S2P 26650 LiFePO4, 42 Wh each; C: 5 Wh survival pack with independent charger |")
    a(f"| Solar | wings: 6 panels x 20 cells (10s2p), Vmp ~24 V, ~24 W each; body cells 0.267 m2 usable; survival string 4s2p |")
    a(f"| Power by scenario | full loads {r['consumed_w']:.1f} W average, safe mode {safe:.1f} W, burn mode 53 W (`docs/mission-simulation.md`) |")
    a("| Separation and inhibits | three independent inhibits (timer, supervisor, separation switch); remove-before-flight pin; no RF emission and no deployment until at least 30 minutes after separation (typical rideshare rule, to confirm) |")
    a("| Ground access | umbilical/charge and data port on a rail-accessible connector (design item, not yet detailed) |")
    a("")
    a("## 3. Data and command interfaces")
    a("")
    a("| Item | Value |")
    a("|---|---|")
    a("| Packet format | CCSDS Space Packet with Ginkgo secondary header, CRC-16, signed telecommands (Ed25519), 27 messages (`docs/protocol-messages.md`) |")
    a("| Onboard buses | CAN-FD A and B control plane; Gigabit Ethernet data plane between the Linux computers, MMU and the S-band modem |")
    a(f"| UHF | 433 MHz amateur band, LoRa/AX.25 beacon and commands, about {link['uhf_rate_bps'] / 1000:.0f} kbps |")
    a(f"| S-band | 2.4 GHz amateur band, {link['sband_rate_bps'] / 1e6:.1f} Mbps design rate (250 kbps - 2 Mbps adaptive), efficiency {link['link_efficiency']} |")
    a(f"| Reference ground station | Pamukkale (37.9 N, 29.1 E): {link['passes_per_station_day']} passes/day of {link['pass_s']} s |")
    a("| Data products | CFDP file transfer, `.gpk` archive files and JSON index (`docs/protocol.md`) |")
    a("")
    a("## 4. Thermal interfaces")
    a("")
    a("| Item | Value |")
    a("|---|---|")
    a("| Effective face emissivity | about 0.5 (cells plus MLI patches); telescope column faces alpha 0.2 / eps 0.3 (`configs/12u_thermal.toml`) |")
    a("| Predicted ranges | electronics -10 to +33 C, battery 4 to 15 C, telescope column 13 to 25 C in nominal and eclipse orbits (`docs/thermal.md`) |")
    a("| Heaters | battery 6 W thermostat (4/9 C), telescope column 8 W (14/17 C), survival heaters 2 W |")
    a("| Conduction path | column bulkheads and spine; propulsion bay isolated; dispenser contact through the rails only |")
    a("")
    a("## 5. Structural and environmental design levels")
    a("")
    la = st["launch"]
    a("| Item | Value |")
    a("|---|---|")
    a(f"| Quasi-static design load | {la['quasi_static_g']:.0f} g all axes (local amplification {la['local_amplification']:.0f}x) |")
    a(f"| Random vibration | flat {la['random_asd_g2_per_hz']} g2/Hz, 20-2000 Hz (8.9 Grms) |")
    a(f"| Minimum first mode | {la['minimum_first_mode_hz']:.0f} Hz (estimated frame ~900 Hz, wall panels ~170 Hz, stowed wing ~190 Hz with mid posts) |")
    a("| Radiation | TID target 30 krad for the control electronics with the vault; COTS compute treated as consumables (`docs/longevity.md`) |")
    a("")
    a("## 6. Launch and dispenser interface (assumptions)")
    a("")
    a("| Item | Assumption |")
    a("|---|---|")
    a("| Dispenser | 12U rail-type dispenser compatible with the CubeSat Design Specification rails; contact only on the rails |")
    a("| Orbit | dawn-dusk sun-synchronous, about 700 km (preferred); lifetime and disposal in `docs/orbit-and-debris.md` |")
    a("| Loads | provider's specification replaces the design levels above |")
    a("| Materials | outgassing-screened (TML < 1 %, CVCM < 0.1 %); no ahead-of-time pressurised vessels (iodine is a solid at low pressure); battery safety data package required |")
    a("| Regulatory | frequency coordination and licensing before launch, operator of record (`mission/requirements.md`, REG-1, COLAV-1) |")
    a("")
    a("## 7. Open interface items")
    a("")
    a("- Fix the lengths and deployment mechanisms of the magnetometer boom and the UHF antenna; add them to the CAD model.")
    a("- Define the umbilical connector, RBF pin and separation-switch locations on the rails.")
    a("- Replace assumptions in section 6 with the provider's interface requirements document.")
    a("- Vendor CAD and datasheets for the thruster, telescope optics and wheels; update the module envelopes and the electrical current limits.")
    open(os.path.join(ROOT, "docs", "icd.md"), "w", encoding="utf-8").write("\n".join(L) + "\n")
    print("wrote docs/icd.md")


if __name__ == "__main__":
    main()
