"""Generate docs/orbit-and-debris.md from sim/orbit_life.analysis() so no number in the document can go stale.

Usage: python tools/gen_orbit_doc.py
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "sim"))
import orbit_life as ol  # noqa: E402


def rng(t):
    return f"{t[0]:.0f} - {t[1]:.0f}" if t[1] < 300 else "> 300"


def main():
    o = ol.analysis()
    D = o["decay"]
    p = o["plan"]
    L = ["# Orbit lifetime and debris compliance (generated)", "",
         "Generated by `python tools/gen_orbit_doc.py` from `sim/orbit_life.py`; do not edit by hand. Atmosphere: two exponential tables (solar minimum and maximum, log interpolation) with an 11-year cycle; accuracy a factor 2-3. "
         "For licensing use NRLMSISE-00 or JB2008 with a solar-flux forecast, or ESA DRAMA / NASA DAS.", "",
         f"Spacecraft mass {o['mass']:.1f} kg (from the configuration), Cd {o['cd']}; tumbling projected area: body {o['body_area']:.2f} m2, wings {o['wings_avg']:.2f} m2 (double-sided plates average half their area), sail {o['sail_avg']:.2f} m2 for a 1 m2 flat sail.", "",
         "## Natural decay to 200 km (years; best and worst starting phase of the solar cycle)", "",
         "| Altitude | " + " | ".join(o["cases"]) + " |", "|---|---|---|---|"]
    for h in (500, 600, 700, 800):
        L.append(f"| {h} km | " + " | ".join(rng(D[(h, c)]) for c in o["cases"]) + " |")
    L += ["", "## Drag make-up delta-v (wings deployed, averaged over the solar cycle)", "", "| Altitude | m/s per year | 50 years |", "|---|---|---|"]
    for h in (500, 600, 700, 800):
        avg = o["dv"][h][0]
        L.append(f"| {h} km | {avg:.1f} | {avg * 50:.0f} m/s |")
    y_w, y_s = D[(700, "wings deployed")], D[(700, "wings + 1 m2 drag sail")]
    d6, d5 = o["descent"][600], o["descent"][500]
    L += ["", "## Disposal from 700 km (IADC guideline: 25 years)", "",
          f"- Passive with wings only: {y_w[0]:.0f}-{y_w[1]:.0f} years: **fails**.",
          f"- Passive with a 1 m2 sail: {y_s[0]:.0f}-{y_s[1]:.0f} years: meets 25 years on this model, but the uncertainty (factor 2-3) could push it above 25; treat the sail as the passive backup, not the plan.",
          f"- **Propulsive descent** with the electric thruster: 700 -> 600 km costs {d6['dv']:.0f} m/s (~{d6['days']:.0f} days of thrusting at 1.1 mN, then {d6['years'][0]:.0f}-{d6['years'][1]:.0f} years of drag with the sail); "
          f"700 -> 500 km costs {d5['dv']:.0f} m/s (~{d5['days']:.0f} days, then {d5['years'][0]:.1f}-{d5['years'][1]:.1f} years). A perigee-lowering burn to 300 km costs {o['perigee']['dv']:.0f} m/s (~{o['perigee']['days']:.0f} days).",
          f"- Delta-v plan at 700 km: {p['keeping_50y']:.0f} m/s station keeping x1.5 margin ({p['keeping_margin']:.0f}) + {p['descent']:.0f} m/s descent + {p['avoidance']:.0f} m/s collision avoidance = **{p['total']:.0f} m/s of {o['available_dv']:.0f} m/s available** "
          f"({ol.IMPULSE_NS:.0f} Ns class thruster on {o['mass']:.1f} kg; `docs/propulsion.md`).",
          "- 800 km and above would need propulsion for disposal (passive decay takes decades to centuries) and are not recommended without a disposal plan.", "",
          "## Consequences for the design", "",
          f"- The drag sail is required, not optional (also as the passive backup if propulsion fails at end of life); the propulsion bay keeps propellant reserved for the descent (about {d5['dv']:.0f} m/s).",
          f"- 600 km is technically possible for 50 years ({o['dv'][600][0] * 50:.0f} m/s) but leaves a smaller margin against collision-avoidance needs; 700 km balances lifetime and disposal.",
          "- Collision risk with catalogued and uncatalogued debris is **not evaluated**: run ESA MASTER / NASA ORDEM for the chosen orbit and use the conjunction data messages (`mission/requirements.md`, COLAV).", "",
          "## Open items", "",
          "- Replace the atmosphere model with NRLMSISE-00 / JB2008 and a solar-flux forecast; include attitude-dependent area (a stable attitude changes the area by a factor of 2-4).",
          "- Debris flux and probability of collision for a 50-year mission at 700 km; end-of-life passivation (deplete propellant, discharge batteries) and its effect on the survival chain that is meant to outlive the mission.",
          "- **Conflict to resolve (LONG-4):** a 50-year mission conflicts with the 25-year disposal guideline. The 50-year figure is a design life of the survival chain; the operational life ends with a disposal manoeuvre "
          "(or a documented exception), so the 50-year tier applies to the platform design, not to the flight article of this orbit.", ""]
    open(os.path.join(ROOT, "docs", "orbit-and-debris.md"), "w", encoding="utf-8").write("\n".join(L))
    print("wrote docs/orbit-and-debris.md")


if __name__ == "__main__":
    main()
