"""Generate docs/layout.md from the real geometric placement, mass properties, thermal loads and layout rules.

Usage: python tools/gen_layout_doc.py     (run mechanical/pack.py first so mechanical/out/placement.json is current)
"""
import json
import os
import subprocess
import sys
import tomllib

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "sim"))
sys.path.insert(0, os.path.join(ROOT, "mechanical"))
import wollemi_cad as gc  # noqa: E402
import thermal as T  # noqa: E402


def load(p):
    return tomllib.load(open(os.path.join(ROOT, p), "rb"))


def main():
    cfg = load("configs/12u_science.toml")
    geo = load("configs/12u_geometry.toml")
    placement = json.load(open(os.path.join(ROOT, "mechanical", "out", "placement.json")))
    placed = placement["placed"]
    deck_h = placement["inner_z"] / 3
    M, com, inertia = gc.mass_props(placed, cfg, False, geo)
    rules = subprocess.run([sys.executable, os.path.join(ROOT, "sim", "layout_check.py")], capture_output=True, text=True, cwd=ROOT).stdout
    rule_lines = [l for l in rules.splitlines() if l.startswith("[")]
    fill_line = next((l for l in rules.splitlines() if l.startswith("Column totals")), "")
    names = {1: "telescope column", 2: "attitude, small Earth optics, ballast", 3: "compute, comms, quiet science", 4: "energy vault, hard-radiation science"}

    L = ["# 12U internal layout (generated)", "",
         "Generated by `python tools/gen_layout_doc.py` from `mechanical/out/placement.json` (the real packing of `mechanical/pack.py`), the mass properties of the CAD model and the thermal loads of `sim/thermal.py`. "
         "Do not edit by hand; the layout intent lives in `configs/12u_layout.toml` and `configs/12u_geometry.toml`.", "",
         "Envelope 226.3 x 226.3 x 340.5 mm = 2 x 2 x 3 cells (columns Q1-Q4 around the central spine; D1 nadir end to D3 zenith end). Cards are 100 x 100 mm with a 20 mm spine notch, an 8 mm outer-corner relief "
         "and a 4 mm backplane gap.", "",
         f"Interior occupancy: {len(placed)} modules, {M:.2f} kg, centre of mass ({com[0]:+.1f}, {com[1]:+.1f}, {com[2]:+.1f}) mm from the geometric centre (limits +-20 mm x/y, +-70 mm z). {fill_line}", ""]
    for q in (1, 2, 3, 4):
        mods = sorted((p for p in placed if p["col"] == q), key=lambda p: p["min"][2])
        heat = T.col_power[q]
        L += [f"## Column Q{q}: {names[q]}", "",
              f"{len(mods)} modules, {sum(p['mass_kg'] for p in mods):.2f} kg, average dissipation about {heat:.1f} W.", "",
              "| Deck | z range (mm) | Module | Size (mm) | Mass kg |", "|---|---|---|---|---|"]
        for p in mods:
            z0, z1 = p["min"][2] - 3.0, p["max"][2] - 3.0
            d1, d2 = int(z0 // deck_h) + 1, int((z1 - 0.01) // deck_h) + 1
            deck = f"D{d1}" if d1 == d2 else f"D{d1}-D{d2}"
            s = p["size"]
            L.append(f"| {deck} | {p['min'][2]:.0f} - {p['max'][2]:.0f} | {p['name'][:78]} | {s[0]:.0f} x {s[1]:.0f} x {s[2]:.0f} | {p['mass_kg']:.2f} |")
        L.append("")
    bay = [p for p in placed if p["col"] == 0]
    if bay:
        b = bay[0]
        L += ["## Propulsion bay (between Q2 and Q3)", "",
              f"{b['name'][:100]}: cylinder along X on the -X face centre line, {b['size'][0]:.0f} x {b['size'][1]:.0f} mm, {b['mass_kg']:.2f} kg; keep-out in Q2 and Q3; nozzle canted through the centre of mass (`docs/adcs.md`).", ""]
    L += ["## Outside the cells", "",
          "Skin: solar cells (body), retroreflector, memory plate, material exposure plate. Spine: harness. Backplane strips: one per column on the bulkhead wall (`docs/electrical-interface.md`).", "",
          "## Separation and layout rules (checked automatically by `sim/layout_check.py`)", ""]
    L += [f"- `{l}`" for l in rule_lines]
    L += ["", "## Balance and thermal", "",
          f"- Column masses (kg): " + ", ".join(f"Q{q} {T.col_mass[q]:.2f}" for q in (1, 2, 3, 4)) + f"; battery {T.batt_mass:.2f}; propulsion bay {T.tank_mass:.2f}.",
          "- Average heat per column (W): " + ", ".join(f"Q{q} {T.col_power[q]:.1f}" for q in (1, 2, 3, 4)) + f" (total {sum(T.col_power.values()):.1f} W); temperatures in `docs/thermal.md`.",
          "- A 1.7 kg tungsten ballast in the Q2 strip trims the centre of mass; the thrust line passes through it via the fixed nozzle cant (`docs/adcs.md`).", "",
          "## Open items", "",
          "- Bounding boxes are estimates: replace with vendor CAD; re-run `mechanical/reconcile.py` and the interference check after every change.",
          "- Cable routing through the spine and connector access; radiator and MLI patch layout on the faces (effective emissivity about 0.5)."]
    open(os.path.join(ROOT, "docs", "layout.md"), "w", encoding="utf-8").write("\n".join(L) + "\n")
    print("wrote docs/layout.md")


if __name__ == "__main__":
    main()
